M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date Mon 24 Jul 2023 05:29:28 PM MDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-24T17:29:28-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.3445Y-4.7441
X5.4134Y-3.7205
X7.2539Y-3.7894
T0
M30
